//! Builtin metadata catalog — set-theoretic / structural information about
//! every Rust-implemented builtin.
//!
//! Phase 9 goal: make seki tests reason about builtins as **mathematical
//! functions over sets** rather than opaque procedures.  Each entry exposes:
//!
//!   * `signature` — domain → codomain in set-theoretic notation
//!   * `domain` / `codomain` — set names (concrete or refinement)
//!   * `effect`     — Pure / Read / Write / Mutate / Concurrent / Unsafe / Meta
//!   * `properties` — known structural invariants (commutative, associative,
//!                    total, monotonic, length-preserving, etc.)
//!   * `doc`        — one-line human description
//!
//! Test code can query this via seki-side `builtinDoc` / `builtinSig` /
//! `builtinEffect` / `builtinProperties` to write property-first tests
//! anchored on the **Rust author's stated invariants**.
//!
//! When a builtin lacks an entry, the lookup returns `None` and the test
//! treats it as "unspecified" (which itself can be a checkable assertion:
//! "every builtin we care about has metadata").

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Effect {
    /// No side effects.  Deterministic.  Same args → same result, no globals
    /// touched, no I/O, no panic on well-typed input.
    Pure,
    /// Pure on the well-typed subset, but can panic / return Err on edge
    /// inputs (e.g. `sqrt(-1)`, `1/0`, FFI-bad-symbol).
    PartialPure,
    /// Reads from the world: file system, environment, clock, RNG state,
    /// socket recv.  Does not mutate.
    Read,
    /// Writes to the world: file, stdout/stderr, socket send, `exit`,
    /// process spawn.
    Write,
    /// Reads and writes seki-managed mutable state: `Ref`, `Dict`, `Atomic*`.
    /// Distinct from `Write` (which targets the OS).
    Mutate,
    /// Cross-thread primitives: `spawn`, `join`, `parMap`, channel ops, TCP.
    /// Effect-wise these are a superset of Mutate + Read + Write.
    Concurrent,
    /// FFI / unsafe.  Behavior depends on user-provided foreign code.
    Unsafe,
    /// Compiler / VM / SMT meta-operations.  Pure with respect to seki's
    /// own runtime state but reflect on seki source / value structure.
    Meta,
}

impl Effect {
    pub fn name(self) -> &'static str {
        match self {
            Effect::Pure        => "Pure",
            Effect::PartialPure => "PartialPure",
            Effect::Read        => "Read",
            Effect::Write       => "Write",
            Effect::Mutate      => "Mutate",
            Effect::Concurrent  => "Concurrent",
            Effect::Unsafe      => "Unsafe",
            Effect::Meta        => "Meta",
        }
    }
}

/// Stored metadata for one builtin function.  All fields are `'static` so
/// the entire catalog is compile-time data with zero runtime cost.
#[derive(Debug, Clone, Copy)]
pub struct BuiltinMeta {
    pub name: &'static str,
    /// Human-readable signature in set-theoretic notation.  Example:
    /// `"strLen : String -> Nat"`, `"readFile : String -> IO (Result String String)"`.
    pub signature: &'static str,
    /// Comma-separated domain set names — one per argument.
    /// Example for `dictInsert : K -> V -> Dict K V -> Dict K V` → `"K, V, Dict K V"`.
    pub domain: &'static str,
    /// Codomain set name.  Mirrors the rightmost part of `signature`.
    pub codomain: &'static str,
    pub effect: Effect,
    /// Known structural invariants.  Free-form strings; common conventions:
    /// `"total"`, `"commutative"`, `"associative"`, `"idempotent"`,
    /// `"monotonic"`, `"injective"`, `"surjective"`, `"involutive"`,
    /// `"length-preserving"`, `"length-additive"`, `"order-preserving"`,
    /// `"functional-update"` (Dict update returns a new value, doesn't mutate
    /// input), `"deterministic"`, `"reentrant"`.
    pub properties: &'static [&'static str],
    pub doc: &'static str,
}

/// Lookup the metadata for a builtin by name.  Returns `None` for builtins
/// without a catalog entry — that's a documentation hole worth fixing, not
/// a runtime bug.
pub fn builtin_meta(name: &str) -> Option<BuiltinMeta> {
    Some(match name {
        // ----- Tuple primitives ---------------------------------------------
        "fst" => BuiltinMeta {
            name: "fst",
            signature: "fst : (A × B) -> A",
            domain: "A × B",
            codomain: "A",
            effect: Effect::Pure,
            properties: &["total", "projection-1"],
            doc: "First element of a tuple.",
        },
        "snd" => BuiltinMeta {
            name: "snd",
            signature: "snd : (A × B) -> B",
            domain: "A × B",
            codomain: "B",
            effect: Effect::Pure,
            properties: &["total", "projection-2"],
            doc: "Second element of a tuple.",
        },
        "pair" => BuiltinMeta {
            name: "pair",
            signature: "pair : A -> B -> (A × B)",
            domain: "A, B",
            codomain: "A × B",
            effect: Effect::Pure,
            properties: &["total", "constructor", "fst-snd-inverse"],
            doc: "Build a 2-tuple. fst (pair a b) = a, snd (pair a b) = b.",
        },

        // ----- Set primitives -----------------------------------------------
        "card" => BuiltinMeta {
            name: "card",
            signature: "card : Set -> Nat",
            domain: "Set (enumerated only)",
            codomain: "Nat",
            effect: Effect::PartialPure,
            properties: &["nonneg"],
            doc: "Cardinality of an enumerated set. Errors on Comp / infinite sets.",
        },
        "List" => BuiltinMeta {
            name: "List",
            signature: "List : Set -> Set",
            domain: "Set",
            codomain: "Set",
            effect: Effect::Pure,
            properties: &["set-constructor", "functor"],
            doc: "List type constructor. List(T) = ⋃ₙ Tⁿ.",
        },
        "Tree" => BuiltinMeta {
            name: "Tree",
            signature: "Tree : Set -> Set",
            domain: "Set",
            codomain: "Set",
            effect: Effect::Pure,
            properties: &["set-constructor"],
            doc: "Tree type constructor.  Tree(T) = {leaf} ∪ Tree(T)×T×Tree(T).",
        },
        "IO" => BuiltinMeta {
            name: "IO",
            signature: "IO : Set -> Set",
            domain: "Set",
            codomain: "Set",
            effect: Effect::Meta,
            properties: &["identity-marker"],
            doc: "Effect marker. Currently IO A == A; reserved for future enforcement.",
        },

        // ----- Numeric ------------------------------------------------------
        "intToReal" => BuiltinMeta {
            name: "intToReal",
            signature: "intToReal : Int -> Real",
            domain: "Int",
            codomain: "Real",
            effect: Effect::Pure,
            properties: &["total", "injective", "monotonic", "embedding"],
            doc: "Int ⊆ Real via the canonical embedding.",
        },
        "floor" => BuiltinMeta {
            name: "floor",
            signature: "floor : Real -> Int",
            domain: "Real",
            codomain: "Int",
            effect: Effect::Pure,
            properties: &["total", "monotonic", "idempotent-after-intToReal"],
            doc: "Floor: largest integer ≤ argument.",
        },
        "ceil" => BuiltinMeta {
            name: "ceil",
            signature: "ceil : Real -> Int",
            domain: "Real",
            codomain: "Int",
            effect: Effect::Pure,
            properties: &["total", "monotonic"],
            doc: "Ceiling: smallest integer ≥ argument.",
        },
        "round" => BuiltinMeta {
            name: "round",
            signature: "round : Real -> Int",
            domain: "Real",
            codomain: "Int",
            effect: Effect::Pure,
            properties: &["total"],
            doc: "Round to nearest integer (half away from zero).",
        },
        "sqrt" => BuiltinMeta {
            name: "sqrt",
            signature: "sqrt : {x in Real | x >= 0} -> Real",
            domain: "Real (nonneg)",
            codomain: "Real",
            effect: Effect::PartialPure,
            properties: &["monotonic", "right-inverse-of-square"],
            doc: "Square root. Errors on negative argument.",
        },
        "pow" => BuiltinMeta {
            name: "pow",
            signature: "pow : Numeric -> Numeric -> Numeric",
            domain: "Numeric, Numeric",
            codomain: "Numeric",
            effect: Effect::PartialPure,
            properties: &["pow-1-is-identity", "pow-0-is-1"],
            doc: "Exponentiation. Errors on Int^negative-Int.",
        },

        // ----- Bit operations -----------------------------------------------
        "bitAnd" => BuiltinMeta {
            name: "bitAnd",
            signature: "bitAnd : Int -> Int -> Int",
            domain: "Int, Int",
            codomain: "Int",
            effect: Effect::Pure,
            properties: &["total", "commutative", "associative", "idempotent",
                          "absorbs-with-zero"],
            doc: "Bitwise AND on 64-bit signed integers.",
        },
        "bitOr" => BuiltinMeta {
            name: "bitOr",
            signature: "bitOr : Int -> Int -> Int",
            domain: "Int, Int",
            codomain: "Int",
            effect: Effect::Pure,
            properties: &["total", "commutative", "associative", "idempotent",
                          "identity-with-zero"],
            doc: "Bitwise OR.",
        },
        "bitXor" => BuiltinMeta {
            name: "bitXor",
            signature: "bitXor : Int -> Int -> Int",
            domain: "Int, Int",
            codomain: "Int",
            effect: Effect::Pure,
            properties: &["total", "commutative", "associative",
                          "self-inverse", "identity-with-zero"],
            doc: "Bitwise XOR. a xor a == 0, a xor 0 == a.",
        },
        "bitNot" => BuiltinMeta {
            name: "bitNot",
            signature: "bitNot : Int -> Int",
            domain: "Int",
            codomain: "Int",
            effect: Effect::Pure,
            properties: &["total", "involutive"],
            doc: "Bitwise NOT (one's complement).",
        },
        "bitShl" => BuiltinMeta {
            name: "bitShl",
            signature: "bitShl : Int -> Int -> Int",
            domain: "Int, Int (0..63)",
            codomain: "Int",
            effect: Effect::Pure,
            properties: &["total", "shift-0-is-identity"],
            doc: "Logical shift left (saturates at 63).",
        },
        "bitShr" => BuiltinMeta {
            name: "bitShr",
            signature: "bitShr : Int -> Int -> Int",
            domain: "Int, Int (0..63)",
            codomain: "Int",
            effect: Effect::Pure,
            properties: &["total", "shift-0-is-identity"],
            doc: "Logical shift right (saturates at 63).",
        },
        "popcount" => BuiltinMeta {
            name: "popcount",
            signature: "popcount : Int -> Nat",
            domain: "Int",
            codomain: "{n in Nat | n <= 64}",
            effect: Effect::Pure,
            properties: &["total", "popcount-zero-is-zero"],
            doc: "Number of 1-bits in the 64-bit representation.",
        },

        // ----- String operations -------------------------------------------
        "strLen" => BuiltinMeta {
            name: "strLen",
            signature: "strLen : String -> Nat",
            domain: "String",
            codomain: "Nat",
            effect: Effect::Pure,
            properties: &["total", "strLen-empty-is-zero",
                          "strLen-additive-under-strConcat"],
            doc: "Number of UTF-8 characters (not bytes).",
        },
        "strConcat" => BuiltinMeta {
            name: "strConcat",
            signature: "strConcat : String -> String -> String",
            domain: "String, String",
            codomain: "String",
            effect: Effect::Pure,
            properties: &["total", "associative", "left-identity-empty",
                          "right-identity-empty", "length-additive"],
            doc: "Concatenation. (String, strConcat, \"\") is a monoid.",
        },
        "strIndexOf" => BuiltinMeta {
            name: "strIndexOf",
            signature: "strIndexOf : String -> String -> Int",
            domain: "String, String",
            codomain: "Int (≥ -1)",
            effect: Effect::Pure,
            properties: &["total"],
            doc: "First index of needle in haystack, or -1 if not present.",
        },
        "strReplace" => BuiltinMeta {
            name: "strReplace",
            signature: "strReplace : String -> String -> String -> String",
            domain: "String, String, String",
            codomain: "String",
            effect: Effect::Pure,
            properties: &["total", "strReplace-x-x-is-id"],
            doc: "Replace all occurrences of `old` with `new` in `s`.",
        },
        "strSplit" => BuiltinMeta {
            name: "strSplit",
            signature: "strSplit : String -> String -> List String",
            domain: "String, String",
            codomain: "List String",
            effect: Effect::Pure,
            properties: &["total", "strSplit-strJoin-roundtrip-with-delim"],
            doc: "Split by delimiter. strJoin delim (strSplit delim s) == s.",
        },
        "substring" => BuiltinMeta {
            name: "substring",
            signature: "substring : Int -> Int -> String -> String",
            domain: "Int, Int, String",
            codomain: "String",
            effect: Effect::Pure,
            properties: &["total", "substring-0-len-is-id"],
            doc: "Extract substring(start, length) in UTF-8 character units.",
        },
        "strToUpper" => BuiltinMeta {
            name: "strToUpper",
            signature: "strToUpper : String -> String",
            domain: "String",
            codomain: "String",
            effect: Effect::Pure,
            properties: &["total", "idempotent", "length-changes-possible"],
            doc: "Unicode case fold to upper case.",
        },
        "strToLower" => BuiltinMeta {
            name: "strToLower",
            signature: "strToLower : String -> String",
            domain: "String",
            codomain: "String",
            effect: Effect::Pure,
            properties: &["total", "idempotent", "length-changes-possible"],
            doc: "Unicode case fold to lower case.",
        },
        "strTrim" => BuiltinMeta {
            name: "strTrim",
            signature: "strTrim : String -> String",
            domain: "String",
            codomain: "String",
            effect: Effect::Pure,
            properties: &["total", "idempotent"],
            doc: "Remove leading and trailing whitespace.",
        },
        "strChars" => BuiltinMeta {
            name: "strChars",
            signature: "strChars : String -> List String",
            domain: "String",
            codomain: "List String",
            effect: Effect::Pure,
            properties: &["total", "length-equals-strLen"],
            doc: "Each UTF-8 character as a one-character string.",
        },
        "intToStr" => BuiltinMeta {
            name: "intToStr",
            signature: "intToStr : Int -> String",
            domain: "Int",
            codomain: "String",
            effect: Effect::Pure,
            properties: &["total", "injective"],
            doc: "Decimal representation of an Int.",
        },
        "realToStr" => BuiltinMeta {
            name: "realToStr",
            signature: "realToStr : Real -> String",
            domain: "Real",
            codomain: "String",
            effect: Effect::Pure,
            properties: &["total"],
            doc: "Decimal representation of a Real.",
        },
        "strToInt" => BuiltinMeta {
            name: "strToInt",
            signature: "strToInt : String -> Option Int",
            domain: "String",
            codomain: "Option Int",
            effect: Effect::Pure,
            properties: &["total", "right-inverse-of-intToStr"],
            doc: "Parse a decimal Int.  None on malformed input.",
        },
        "strToReal" => BuiltinMeta {
            name: "strToReal",
            signature: "strToReal : String -> Option Real",
            domain: "String",
            codomain: "Option Real",
            effect: Effect::Pure,
            properties: &["total"],
            doc: "Parse a Real.  None on malformed input.",
        },
        "toStr" => BuiltinMeta {
            name: "toStr",
            signature: "toStr : Any -> String",
            domain: "Any",
            codomain: "String",
            effect: Effect::Pure,
            properties: &["total"],
            doc: "Display any value as its canonical string form.",
        },

        // ----- File I/O -----------------------------------------------------
        "readFile" => BuiltinMeta {
            name: "readFile",
            signature: "readFile : String -> IO (Result String String)",
            domain: "String",
            codomain: "Result String String",
            effect: Effect::Read,
            properties: &["partial"],
            doc: "Read entire file contents.  Err on I/O failure.",
        },
        "writeFile" => BuiltinMeta {
            name: "writeFile",
            signature: "writeFile : String -> String -> IO (Result Unit String)",
            domain: "String, String",
            codomain: "Result Unit String",
            effect: Effect::Write,
            properties: &["overwrites"],
            doc: "Write contents to file (replaces existing).",
        },
        "appendFile" => BuiltinMeta {
            name: "appendFile",
            signature: "appendFile : String -> String -> IO (Result Unit String)",
            domain: "String, String",
            codomain: "Result Unit String",
            effect: Effect::Write,
            properties: &["additive"],
            doc: "Append to file (creates if missing).",
        },
        "fileExists" => BuiltinMeta {
            name: "fileExists",
            signature: "fileExists : String -> IO Bool",
            domain: "String",
            codomain: "Bool",
            effect: Effect::Read,
            properties: &["total"],
            doc: "Test if a path refers to an existing file or directory.",
        },
        "removeFile" => BuiltinMeta {
            name: "removeFile",
            signature: "removeFile : String -> IO (Result Unit String)",
            domain: "String",
            codomain: "Result Unit String",
            effect: Effect::Write,
            properties: &["destructive"],
            doc: "Delete a file.  Err if the path doesn't exist.",
        },

        // ----- stdio --------------------------------------------------------
        "print" => BuiltinMeta {
            name: "print",
            signature: "print : Any -> IO Unit",
            domain: "Any",
            codomain: "Unit",
            effect: Effect::Write,
            properties: &["writes-stdout", "no-newline", "may-buffer"],
            doc: "Write value to stdout without trailing newline.",
        },
        "println" => BuiltinMeta {
            name: "println",
            signature: "println : Any -> IO Unit",
            domain: "Any",
            codomain: "Unit",
            effect: Effect::Write,
            properties: &["writes-stdout", "appends-newline", "may-buffer"],
            doc: "Write value to stdout with trailing newline.",
        },
        "eprint" => BuiltinMeta {
            name: "eprint",
            signature: "eprint : Any -> IO Unit",
            domain: "Any",
            codomain: "Unit",
            effect: Effect::Write,
            properties: &["writes-stderr", "no-newline"],
            doc: "Write value to stderr without trailing newline.",
        },
        "eprintln" => BuiltinMeta {
            name: "eprintln",
            signature: "eprintln : Any -> IO Unit",
            domain: "Any",
            codomain: "Unit",
            effect: Effect::Write,
            properties: &["writes-stderr", "appends-newline"],
            doc: "Write value to stderr with trailing newline.",
        },
        "readLine" => BuiltinMeta {
            name: "readLine",
            signature: "readLine : Unit -> IO (Option String)",
            domain: "Unit",
            codomain: "Option String",
            effect: Effect::Read,
            properties: &["blocking", "may-return-none-on-eof", "strips-trailing-newline"],
            doc: "Read one line from stdin. None on EOF, Some s otherwise (LF/CRLF stripped).",
        },

        // ----- OS / process -------------------------------------------------
        "args" => BuiltinMeta {
            name: "args",
            signature: "args : List String",
            domain: "(global)",
            codomain: "List String",
            effect: Effect::Pure,
            properties: &["constant-per-program-run", "set-by-main"],
            doc: "CLI arguments after the file path (or after `--`).",
        },
        "getEnv" => BuiltinMeta {
            name: "getEnv",
            signature: "getEnv : String -> IO (Option String)",
            domain: "String (env var name)",
            codomain: "Option String",
            effect: Effect::Read,
            properties: &["total", "may-return-none"],
            doc: "Read environment variable. None if not set.",
        },
        "exit" => BuiltinMeta {
            name: "exit",
            signature: "exit : Int -> Never",
            domain: "Int (exit code)",
            codomain: "Never",
            effect: Effect::Write,
            properties: &["never-returns", "terminates-process", "no-cleanup-guaranteed"],
            doc: "Terminate the process immediately with the given exit code.",
        },
        "execShell" => BuiltinMeta {
            name: "execShell",
            signature: "execShell : String -> IO (Result String String)",
            domain: "String (shell command)",
            codomain: "Result String String",
            effect: Effect::Write,
            properties: &["spawns-child", "shell-injection-risk", "blocking",
                          "captures-stdout"],
            doc: "Run command via `sh -c`. Returns stdout on success.",
        },
        "runCommand" => BuiltinMeta {
            name: "runCommand",
            signature: "runCommand : String -> List String -> IO (Int × String × String)",
            domain: "String × List String",
            codomain: "Int × String × String  (exit, stdout, stderr)",
            effect: Effect::Write,
            properties: &["spawns-child", "no-shell-interpretation", "blocking",
                          "captures-stdout-stderr"],
            doc: "Run command + argv directly (no shell expansion).",
        },

        // ----- Time --------------------------------------------------------
        "nowSecs" => BuiltinMeta {
            name: "nowSecs",
            signature: "nowSecs : Unit -> IO Int",
            domain: "Unit",
            codomain: "Int (UNIX epoch seconds)",
            effect: Effect::Read,
            properties: &["wall-clock", "non-deterministic", "monotonic-in-physical-time"],
            doc: "Seconds since UNIX epoch (1970-01-01 UTC). Wall clock.",
        },
        "nowMillis" => BuiltinMeta {
            name: "nowMillis",
            signature: "nowMillis : Unit -> IO Int",
            domain: "Unit",
            codomain: "Int (UNIX epoch ms)",
            effect: Effect::Read,
            properties: &["wall-clock", "non-deterministic"],
            doc: "Milliseconds since UNIX epoch.",
        },
        "nowMicros" => BuiltinMeta {
            name: "nowMicros",
            signature: "nowMicros : Unit -> IO Int",
            domain: "Unit",
            codomain: "Int (UNIX epoch µs)",
            effect: Effect::Read,
            properties: &["wall-clock", "non-deterministic"],
            doc: "Microseconds since UNIX epoch.",
        },
        "monotonicMillis" => BuiltinMeta {
            name: "monotonicMillis",
            signature: "monotonicMillis : Unit -> IO Nat",
            domain: "Unit",
            codomain: "Nat",
            effect: Effect::Read,
            properties: &["monotonic", "non-decreasing", "anchored-at-program-start",
                          "safe-for-elapsed-measurements"],
            doc: "Milliseconds since program start. Use for elapsed time.",
        },
        "sleep" => BuiltinMeta {
            name: "sleep",
            signature: "sleep : {n in Int | n >= 0} -> IO Unit",
            domain: "Int (≥ 0, ms)",
            codomain: "Unit",
            effect: Effect::Write,
            properties: &["blocking", "may-sleep-longer-than-requested",
                          "current-thread-only"],
            doc: "Block the current thread for at least N milliseconds.",
        },

        // ----- Random (xorshift64* PRNG, thread-local state) ----------------
        "randomSeed" => BuiltinMeta {
            name: "randomSeed",
            signature: "randomSeed : Int -> IO Unit",
            domain: "Int (nonzero recommended)",
            codomain: "Unit",
            effect: Effect::Mutate,
            properties: &["thread-local-state", "deterministic-after-seed",
                          "reproducible-with-same-seed"],
            doc: "Set the xorshift64* PRNG seed (thread-local).",
        },
        "randomInt" => BuiltinMeta {
            name: "randomInt",
            signature: "randomInt : Unit -> IO Int",
            domain: "Unit",
            codomain: "Int",
            effect: Effect::Mutate,
            properties: &["xorshift64-star", "thread-local-state",
                          "non-cryptographic", "uniform-64-bit"],
            doc: "Next 64-bit PRNG output. Advances the seed.",
        },
        "randomRange" => BuiltinMeta {
            name: "randomRange",
            signature: "randomRange : Int -> Int -> IO {x in Int | lo <= x and x < hi}",
            domain: "{(lo, hi) in Int × Int | lo < hi}",
            codomain: "Int (in [lo, hi))",
            effect: Effect::Mutate,
            properties: &["in-range", "uniform-modulo-bias-for-large-spans",
                          "thread-local-state"],
            doc: "Random integer in [lo, hi). Slight bias when (hi - lo) is huge.",
        },
        "randomFloat" => BuiltinMeta {
            name: "randomFloat",
            signature: "randomFloat : Unit -> IO {r in Real | 0 <= r and r < 1}",
            domain: "Unit",
            codomain: "Real (in [0, 1))",
            effect: Effect::Mutate,
            properties: &["uniform-53-bit", "in-unit-interval", "thread-local-state"],
            doc: "Random Real in [0, 1) with 53 bits of precision.",
        },

        // ----- Ref ---------------------------------------------------------
        "mkRef" => BuiltinMeta {
            name: "mkRef",
            signature: "mkRef : A -> IO (Ref A)",
            domain: "A",
            codomain: "Ref A",
            effect: Effect::Mutate,
            properties: &["creates-fresh-cell", "fresh-identity"],
            doc: "Allocate a mutable cell with the given initial value.",
        },
        "readRef" => BuiltinMeta {
            name: "readRef",
            signature: "readRef : Ref A -> IO A",
            domain: "Ref A",
            codomain: "A",
            effect: Effect::Read,
            properties: &["pure-after-most-recent-write", "non-blocking-uncontended",
                          "mutex-locked"],
            doc: "Read the cell's current value.",
        },
        "writeRef" => BuiltinMeta {
            name: "writeRef",
            signature: "writeRef : Ref A -> A -> IO Unit",
            domain: "Ref A × A",
            codomain: "Unit",
            effect: Effect::Mutate,
            properties: &["overwrites", "non-blocking-uncontended", "mutex-locked"],
            doc: "Overwrite the cell's value.",
        },

        // ----- Dict (functional, Arc<Mutex<HashMap>> backed) ---------------
        "emptyDict" => BuiltinMeta {
            name: "emptyDict",
            signature: "emptyDict : Unit -> Dict K V",
            domain: "Unit",
            codomain: "Dict K V",
            effect: Effect::Pure,
            properties: &["size-0", "no-keys", "neutral-element-of-dictInsert"],
            doc: "Empty dictionary.",
        },
        "dictInsert" => BuiltinMeta {
            name: "dictInsert",
            signature: "dictInsert : K -> V -> Dict K V -> Dict K V",
            domain: "K × V × Dict K V",
            codomain: "Dict K V",
            effect: Effect::Pure,
            properties: &["functional-update", "overwrite-on-key",
                          "size-monotonic-or-equal", "input-unchanged"],
            doc: "Returns a new Dict with k → v. Input is not mutated.",
        },
        "dictGet" => BuiltinMeta {
            name: "dictGet",
            signature: "dictGet : K -> Dict K V -> Option V",
            domain: "K × Dict K V",
            codomain: "Option V",
            effect: Effect::Pure,
            properties: &["total", "right-inverse-of-dictInsert",
                          "deterministic"],
            doc: "Lookup k. Some v on hit, None on miss.",
        },
        "dictMember" => BuiltinMeta {
            name: "dictMember",
            signature: "dictMember : K -> Dict K V -> Bool",
            domain: "K × Dict K V",
            codomain: "Bool",
            effect: Effect::Pure,
            properties: &["total", "decidable",
                          "equivalent-to-dictGet-isSome"],
            doc: "True iff key is in the dict.",
        },
        "dictRemove" => BuiltinMeta {
            name: "dictRemove",
            signature: "dictRemove : K -> Dict K V -> Dict K V",
            domain: "K × Dict K V",
            codomain: "Dict K V",
            effect: Effect::Pure,
            properties: &["functional-update", "idempotent-on-missing",
                          "size-equal-or-decreases-by-1", "input-unchanged"],
            doc: "Remove k. No-op if absent.",
        },
        "dictSize" => BuiltinMeta {
            name: "dictSize",
            signature: "dictSize : Dict K V -> Nat",
            domain: "Dict K V",
            codomain: "Nat",
            effect: Effect::Pure,
            properties: &["total", "nonneg", "equals-length-of-dictKeys"],
            doc: "Number of entries.",
        },
        "dictKeys" => BuiltinMeta {
            name: "dictKeys",
            signature: "dictKeys : Dict K V -> List K",
            domain: "Dict K V",
            codomain: "List K",
            effect: Effect::Pure,
            properties: &["unspecified-order", "no-duplicates",
                          "length-equals-dictSize"],
            doc: "Keys as a list. Order is HashMap-defined (unspecified).",
        },
        "dictValues" => BuiltinMeta {
            name: "dictValues",
            signature: "dictValues : Dict K V -> List V",
            domain: "Dict K V",
            codomain: "List V",
            effect: Effect::Pure,
            properties: &["same-order-as-dictKeys", "length-equals-dictSize"],
            doc: "Values in matching order to dictKeys.",
        },

        // ----- Concurrency: Atomic ----------------------------------------
        "atomicNew" => BuiltinMeta {
            name: "atomicNew",
            signature: "atomicNew : Int -> IO Atomic",
            domain: "Int",
            codomain: "Atomic",
            effect: Effect::Mutate,
            properties: &["creates-fresh-handle", "Arc-backed", "Send-Sync"],
            doc: "Allocate an Arc<AtomicI64> wrapped in a Handle.",
        },
        "atomicGet" => BuiltinMeta {
            name: "atomicGet",
            signature: "atomicGet : Atomic -> IO Int",
            domain: "Atomic",
            codomain: "Int",
            effect: Effect::Read,
            properties: &["seq-cst", "non-blocking", "lock-free"],
            doc: "Atomic load with SeqCst ordering.",
        },
        "atomicSet" => BuiltinMeta {
            name: "atomicSet",
            signature: "atomicSet : Atomic -> Int -> IO Unit",
            domain: "Atomic × Int",
            codomain: "Unit",
            effect: Effect::Mutate,
            properties: &["seq-cst", "non-blocking", "lock-free", "overwrites"],
            doc: "Atomic store with SeqCst ordering.",
        },
        "atomicAdd" => BuiltinMeta {
            name: "atomicAdd",
            signature: "atomicAdd : Atomic -> Int -> IO Int",
            domain: "Atomic × Int",
            codomain: "Int  (old value)",
            effect: Effect::Mutate,
            properties: &["seq-cst", "fetch-and-add", "associative-net-effect",
                          "lock-free", "wrapping-on-overflow"],
            doc: "Atomic fetch-and-add. Returns old value.",
        },
        "atomicCas" => BuiltinMeta {
            name: "atomicCas",
            signature: "atomicCas : Atomic -> Int -> Int -> IO Bool",
            domain: "Atomic × Int (expected) × Int (new)",
            codomain: "Bool  (true iff swap occurred)",
            effect: Effect::Mutate,
            properties: &["seq-cst", "compare-and-swap", "lock-free", "atomic"],
            doc: "Compare-and-swap. True if exchange succeeded.",
        },

        // ----- Concurrency: spawn / join / parMap --------------------------
        "spawn" => BuiltinMeta {
            name: "spawn",
            signature: "spawn : (() -> A) -> IO (Thread A)",
            domain: "(() -> A)  closure captures must be Send",
            codomain: "Thread A",
            effect: Effect::Concurrent,
            properties: &["creates-fresh-os-thread", "non-blocking-on-spawn",
                          "globals-snapshot-passed-to-child"],
            doc: "Start a new OS thread running the closure. Returns a join handle.",
        },
        "join" => BuiltinMeta {
            name: "join",
            signature: "join : Thread A -> IO A",
            domain: "Thread A (not yet joined)",
            codomain: "A",
            effect: Effect::Concurrent,
            properties: &["blocking", "consumes-handle", "single-call",
                          "propagates-thread-error"],
            doc: "Wait for the thread to finish and return its result.",
        },
        "parMap" => BuiltinMeta {
            name: "parMap",
            signature: "parMap : (A -> B) -> List A -> IO (List B)",
            domain: "(A -> B) × List A",
            codomain: "List B",
            effect: Effect::Concurrent,
            properties: &["order-preserving", "length-preserving",
                          "fresh-thread-per-element", "blocks-until-all-done"],
            doc: "Map in parallel. Output order matches input order.",
        },
        "spawnAtomicAdd" => BuiltinMeta {
            name: "spawnAtomicAdd",
            signature: "spawnAtomicAdd : Atomic -> Int -> Int -> IO Unit",
            domain: "Atomic × Int (delta) × Int (delay_ms ≥ 0)",
            codomain: "Unit",
            effect: Effect::Concurrent,
            properties: &["fire-and-forget", "creates-fresh-os-thread",
                          "sleeps-then-adds"],
            doc: "Spawn a thread that sleeps then atomic-adds delta to the counter.",
        },
        "threadId" => BuiltinMeta {
            name: "threadId",
            signature: "threadId : Unit -> IO String",
            domain: "Unit",
            codomain: "String",
            effect: Effect::Read,
            properties: &["thread-local", "debug-only"],
            doc: "Display the current OS thread's ID. For diagnostics.",
        },

        // ----- Concurrency: mpsc Channel -----------------------------------
        "chanNew" => BuiltinMeta {
            name: "chanNew",
            signature: "chanNew : Unit -> IO (Channel A)",
            domain: "Unit",
            codomain: "Channel A",
            effect: Effect::Concurrent,
            properties: &["creates-fresh-handle", "mpsc",
                          "unbounded-buffer", "sender-cloneable"],
            doc: "Create an unbounded multi-producer single-consumer channel.",
        },
        "chanSend" => BuiltinMeta {
            name: "chanSend",
            signature: "chanSend : Channel A -> A -> IO (Result Unit String)",
            domain: "Channel A × A",
            codomain: "Result Unit String",
            effect: Effect::Concurrent,
            properties: &["non-blocking", "may-fail-receiver-dropped",
                          "fifo-per-sender", "thread-safe"],
            doc: "Send a value. Err if the receiver was dropped.",
        },
        "chanRecv" => BuiltinMeta {
            name: "chanRecv",
            signature: "chanRecv : Channel A -> IO (Result A String)",
            domain: "Channel A",
            codomain: "Result A String",
            effect: Effect::Concurrent,
            properties: &["blocking", "consumes-message",
                          "may-fail-empty-and-all-senders-dropped",
                          "single-consumer"],
            doc: "Receive a value. Blocks until available. Err when channel ends.",
        },
        "chanClose" => BuiltinMeta {
            name: "chanClose",
            signature: "chanClose : Channel A -> IO Unit",
            domain: "Channel A",
            codomain: "Unit",
            effect: Effect::Concurrent,
            properties: &["idempotent", "closes-sender-side"],
            doc: "Drop the sender side, causing future sends to fail.",
        },

        // ----- Network: TCP ------------------------------------------------
        "tcpListen" => BuiltinMeta {
            name: "tcpListen",
            signature: "tcpListen : String -> Int -> IO (Result Listener String)",
            domain: "String × {p in Int | 0 <= p and p <= 65535}",
            codomain: "Result Listener String",
            effect: Effect::Concurrent,
            properties: &["creates-fresh-handle", "binds-to-os-port",
                          "may-fail-EADDRINUSE", "non-blocking-after-bind"],
            doc: "Bind a TCP listener to host:port.",
        },
        "tcpAccept" => BuiltinMeta {
            name: "tcpAccept",
            signature: "tcpAccept : Listener -> IO (Result Socket String)",
            domain: "Listener (open)",
            codomain: "Result Socket String",
            effect: Effect::Concurrent,
            properties: &["blocking", "creates-fresh-handle",
                          "preserves-listener", "single-accept-per-call"],
            doc: "Block until a client connects. Returns one Socket.",
        },
        "tcpConnect" => BuiltinMeta {
            name: "tcpConnect",
            signature: "tcpConnect : String -> Int -> IO (Result Socket String)",
            domain: "String × {p in Int | 0 < p and p <= 65535}",
            codomain: "Result Socket String",
            effect: Effect::Concurrent,
            properties: &["blocking", "creates-fresh-handle",
                          "may-fail-ECONNREFUSED"],
            doc: "Open a client TCP connection.",
        },
        "tcpRead" => BuiltinMeta {
            name: "tcpRead",
            signature: "tcpRead : Socket -> Int -> IO (Result String String)",
            domain: "Socket × {n in Int | n >= 0}",
            codomain: "Result String String  (at most n bytes)",
            effect: Effect::Concurrent,
            properties: &["blocking", "may-return-fewer-bytes-than-requested",
                          "consumes-bytes-from-stream", "utf8-lossy-decode"],
            doc: "Read up to N bytes from the socket. May return less.",
        },
        "tcpWrite" => BuiltinMeta {
            name: "tcpWrite",
            signature: "tcpWrite : Socket -> String -> IO (Result Unit String)",
            domain: "Socket × String",
            codomain: "Result Unit String",
            effect: Effect::Concurrent,
            properties: &["writes-all-or-fails", "blocking", "may-fail-EPIPE"],
            doc: "Write all bytes to the socket.",
        },
        "tcpClose" => BuiltinMeta {
            name: "tcpClose",
            signature: "tcpClose : Handle -> IO Unit",
            domain: "Handle (Socket or Listener)",
            codomain: "Unit",
            effect: Effect::Concurrent,
            properties: &["idempotent", "destructive", "frees-os-resource"],
            doc: "Close a socket or listener. Subsequent ops return Err.",
        },
        "httpGet" => BuiltinMeta {
            name: "httpGet",
            signature: "httpGet : String -> IO (Result String String)",
            domain: "{s in String | startsWith \"http://\" s}",
            codomain: "Result String String  (response body)",
            effect: Effect::Concurrent,
            properties: &["blocking", "no-redirect-follow", "no-tls",
                          "http-1-0-only", "single-connection"],
            doc: "Blocking HTTP/1.0 GET. Returns response body. http:// only.",
        },

        // ----- FFI (Linux/macOS, dlopen-based) -----------------------------
        "ffiLoad" => BuiltinMeta {
            name: "ffiLoad",
            signature: "ffiLoad : String -> IO (Result FfiLib String)",
            domain: "String (.so / .dylib path)",
            codomain: "Result FfiLib String",
            effect: Effect::Unsafe,
            properties: &["dlopen-wrapped", "creates-fresh-handle",
                          "platform-specific-linux-macos", "RTLD_LAZY"],
            doc: "dlopen a shared object. Linux and macOS only.",
        },
        "ffiCallIntInt" => BuiltinMeta {
            name: "ffiCallIntInt",
            signature: "ffiCallIntInt : FfiLib -> String -> Int -> IO (Result Int String)",
            domain: "FfiLib × String (symbol name) × Int (arg)",
            codomain: "Result Int String",
            effect: Effect::Unsafe,
            properties: &["trusts-foreign-abi", "may-segfault-on-mismatch",
                          "type-erasure-at-FFI-boundary"],
            doc: "Call a C function with signature `int(int64_t)`.",
        },
        "ffiCallStrInt" => BuiltinMeta {
            name: "ffiCallStrInt",
            signature: "ffiCallStrInt : FfiLib -> String -> String -> IO (Result Int String)",
            domain: "FfiLib × String × String (auto NUL-terminated)",
            codomain: "Result Int String",
            effect: Effect::Unsafe,
            properties: &["trusts-foreign-abi", "may-segfault-on-mismatch",
                          "auto-cstring-conversion", "null-terminated"],
            doc: "Call a C function with signature `int(const char*)`.",
        },
        "ffiClose" => BuiltinMeta {
            name: "ffiClose",
            signature: "ffiClose : FfiLib -> IO Unit",
            domain: "FfiLib",
            codomain: "Unit",
            effect: Effect::Unsafe,
            properties: &["idempotent", "destructive", "dlclose-wrapped"],
            doc: "dlclose the shared object.",
        },

        // ----- JSON (hand-rolled parser / encoder, zero deps) --------------
        "jsonParse" => BuiltinMeta {
            name: "jsonParse",
            signature: "jsonParse : String -> Result Json String",
            domain: "String",
            codomain: "Result Json String",
            effect: Effect::Pure,
            properties: &["total", "deterministic",
                          "right-inverse-of-jsonEncode-on-roundtrippable",
                          "rejects-trailing-input"],
            doc: "Parse a JSON string. Err with position on malformed input.",
        },
        "jsonEncode" => BuiltinMeta {
            name: "jsonEncode",
            signature: "jsonEncode : Json -> String",
            domain: "Json",
            codomain: "String",
            effect: Effect::Pure,
            properties: &["total", "deterministic", "canonical-form",
                          "jsonParse-roundtrip"],
            doc: "Encode Json ADT to canonical wire-format string.",
        },

        // ----- Meta / Compiler / SMT ---------------------------------------
        "parseSym" => BuiltinMeta {
            name: "parseSym",
            signature: "parseSym : String -> Sym",
            domain: "{s in String | parses as math expression}",
            codomain: "Sym",
            effect: Effect::Meta,
            properties: &["uses-seki-parser", "deterministic",
                          "supports-arith-and-sin-cos-exp-ln-pow"],
            doc: "Parse math notation into Sym ADT tagged-pair encoding.",
        },
        "vmEval" => BuiltinMeta {
            name: "vmEval",
            signature: "vmEval : String -> Result Value String",
            domain: "{s in String | compiles to bytecode subset}",
            codomain: "Result Value String",
            effect: Effect::Meta,
            properties: &["matches-ast-eval-on-vm-subset", "faster-than-tree-walking",
                          "deterministic"],
            doc: "Parse + compile + run on the bytecode VM.",
        },
        "vmTime" => BuiltinMeta {
            name: "vmTime",
            signature: "vmTime : Int -> String -> Int",
            domain: "Int (N ≥ 1) × String",
            codomain: "Int (elapsed ms)",
            effect: Effect::Meta,
            properties: &["benchmark-only", "non-deterministic-timing"],
            doc: "Run N executions on the VM and return elapsed milliseconds.",
        },
        "vmCompiles" => BuiltinMeta {
            name: "vmCompiles",
            signature: "vmCompiles : String -> Bool",
            domain: "String",
            codomain: "Bool",
            effect: Effect::Meta,
            properties: &["total", "deterministic", "decidable"],
            doc: "True iff the expression is in the VM's compilable subset.",
        },
        "linarithProve" => BuiltinMeta {
            name: "linarithProve",
            signature: "linarithProve : String -> List String -> String -> Option Bool",
            domain: "String (focus var) × List String (hyps) × String (goal)",
            codomain: "Option Bool",
            effect: Effect::Meta,
            properties: &["decides-linear-int-1var", "sound-when-Some",
                          "complete-on-decision-class"],
            doc: "Decide a linear-integer implication. None when out of decision class.",
        },
        "linarithCounter" => BuiltinMeta {
            name: "linarithCounter",
            signature: "linarithCounter : String -> List String -> String -> Option Int",
            domain: "String × List String × String",
            codomain: "Option Int (counterexample value)",
            effect: Effect::Meta,
            properties: &["paired-with-linarithProve",
                          "Some-iff-refuted-with-witness"],
            doc: "Return a counterexample integer (or None when goal is provable).",
        },

        // ----- Misc ---------------------------------------------------------
        "error" => BuiltinMeta {
            name: "error",
            signature: "error : String -> A",
            domain: "String (error message)",
            codomain: "A  (Never; control does not return)",
            effect: Effect::Write,
            properties: &["never-returns", "raises-runtime-error",
                          "polymorphic-codomain"],
            doc: "Raise a runtime error with the given message.",
        },

        // ----- Self-reference: the metadata accessors themselves -----------
        "builtinDoc" => BuiltinMeta {
            name: "builtinDoc",
            signature: "builtinDoc : String -> Option String",
            domain: "String (builtin name)",
            codomain: "Option String",
            effect: Effect::Meta,
            properties: &["total", "self-reference", "deterministic"],
            doc: "Look up the doc string for a builtin from this catalog.",
        },
        "builtinSig" => BuiltinMeta {
            name: "builtinSig",
            signature: "builtinSig : String -> Option String",
            domain: "String",
            codomain: "Option String",
            effect: Effect::Meta,
            properties: &["total", "self-reference", "deterministic"],
            doc: "Look up the signature string for a builtin.",
        },
        "builtinEffect" => BuiltinMeta {
            name: "builtinEffect",
            signature: "builtinEffect : String -> Option String",
            domain: "String",
            codomain: "Option String  (one of: Pure / PartialPure / Read / Write / Mutate / Concurrent / Unsafe / Meta)",
            effect: Effect::Meta,
            properties: &["total", "self-reference",
                          "range-is-8-element-enum"],
            doc: "Look up the effect classification for a builtin.",
        },
        "builtinDomain" => BuiltinMeta {
            name: "builtinDomain",
            signature: "builtinDomain : String -> Option String",
            domain: "String",
            codomain: "Option String",
            effect: Effect::Meta,
            properties: &["total", "self-reference"],
            doc: "Look up the (free-form) domain description for a builtin.",
        },
        "builtinCodomain" => BuiltinMeta {
            name: "builtinCodomain",
            signature: "builtinCodomain : String -> Option String",
            domain: "String",
            codomain: "Option String",
            effect: Effect::Meta,
            properties: &["total", "self-reference"],
            doc: "Look up the (free-form) codomain description for a builtin.",
        },
        "builtinProperties" => BuiltinMeta {
            name: "builtinProperties",
            signature: "builtinProperties : String -> List String",
            domain: "String",
            codomain: "List String",
            effect: Effect::Meta,
            properties: &["total", "self-reference", "returns-empty-on-unknown"],
            doc: "Look up the structural-property list for a builtin.",
        },
        "builtinHasProperty" => BuiltinMeta {
            name: "builtinHasProperty",
            signature: "builtinHasProperty : String -> String -> Bool",
            domain: "String (builtin name) × String (property name)",
            codomain: "Bool",
            effect: Effect::Meta,
            properties: &["total", "self-reference", "decidable",
                          "false-on-unknown-builtin"],
            doc: "True iff the builtin declares the named property.",
        },
        "builtinNames" => BuiltinMeta {
            name: "builtinNames",
            signature: "builtinNames : Unit -> List String",
            domain: "Unit",
            codomain: "List String",
            effect: Effect::Meta,
            properties: &["total", "constant", "self-reference",
                          "every-element-has-builtinSig"],
            doc: "Every catalogued builtin name (the documented set).",
        },

        _ => return None,
    })
}

// (Phase 10 cleanup) Removed `meta_simple` / `meta_simple_props` helpers;
// every catalog entry now has a fully-specified domain/codomain/properties
// list, so the placeholder helpers ("(see signature)" fillers) are no
// longer needed.

/// Iterate over all catalogued names.  Used by `seki --builtin-info` to
/// confirm coverage and by tests that want to enumerate builtins.
pub fn all_documented_names() -> &'static [&'static str] {
    &[
        "fst", "snd", "pair", "card", "List", "Tree", "IO",
        "intToReal", "floor", "ceil", "round", "sqrt", "pow",
        "bitAnd", "bitOr", "bitXor", "bitNot", "bitShl", "bitShr", "popcount",
        "strLen", "strConcat", "strIndexOf", "strReplace", "strSplit",
        "substring", "strToUpper", "strToLower", "strTrim", "strChars",
        "intToStr", "realToStr", "strToInt", "strToReal", "toStr",
        "readFile", "writeFile", "appendFile", "fileExists", "removeFile",
        "print", "println", "eprint", "eprintln", "readLine",
        "args", "getEnv", "exit", "execShell", "runCommand",
        "nowSecs", "nowMillis", "nowMicros", "monotonicMillis", "sleep",
        "randomSeed", "randomInt", "randomRange", "randomFloat",
        "mkRef", "readRef", "writeRef",
        "emptyDict", "dictInsert", "dictGet", "dictMember", "dictRemove",
        "dictSize", "dictKeys", "dictValues",
        "spawn", "join", "parMap", "atomicNew", "atomicGet", "atomicSet",
        "atomicAdd", "atomicCas", "chanNew", "chanSend", "chanRecv",
        "chanClose", "spawnAtomicAdd", "threadId",
        "tcpListen", "tcpAccept", "tcpConnect", "tcpRead", "tcpWrite",
        "tcpClose", "httpGet",
        "ffiLoad", "ffiCallIntInt", "ffiCallStrInt", "ffiClose",
        "jsonParse", "jsonEncode",
        "parseSym", "vmEval", "vmTime", "vmCompiles",
        "linarithProve", "linarithCounter",
        "error",
        "builtinDoc", "builtinSig", "builtinEffect", "builtinDomain",
        "builtinCodomain", "builtinProperties", "builtinHasProperty",
        "builtinNames",
    ]
}
